[package]
name = "try5"
version = "0.1.0"
authors = ["Frank Shan <frankqs0304@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
